### ISSUE TITLE
Weather Sample Crash

### ISSUE THREAD

**Issue by cliffgr** [xiane/thingsGpioExample#1]
Hello I have the following issues when i run the sample app of weather in my emulator also i tried to run it on my pi as well.  

`FATAL EXCEPTION: main
                                                                                                    Process: odroid.hardkernel.com.WeatherBoard, PID: 8884
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/things/pio/PeripheralManager;
                                                                                                    	at com.hardkernel.odroid.things.contrib.WeatherBoard.WeatherBoard.<init>(WeatherBoard.java:47)
                                                                                                    	at odroid.hardkernel.com.WeatherBoard.MainActivity.onCreate(MainActivity.java:71)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.things.pio.PeripheralManager" on path: DexPathList[[zip file "/data/app/~~-4kskYJGNxQL5DcLm0lWEw==/odroid.hardkernel.com.WeatherBoard-_bH1ub-KzAdJAs6rePWjVQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~-4kskYJGNxQL5DcLm0lWEw==/odroid.hardkernel.com.WeatherBoard-_bH1ub-KzAdJAs6rePWjVQ==/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.hardkernel.odroid.things.contrib.WeatherBoard.WeatherBoard.<init>(WeatherBoard.java:47) 
                                                                                                    	at odroid.hardkernel.com.WeatherBoard.MainActivity.onCreate(MainActivity.java:71) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) `

I tried to change for compile only to implementation but it seems that i have the following  exception :

![image](https://user-images.githubusercontent.com/4539769/235347824-042d5800-30e1-4de8-acdc-09fb3f0ed9d2.png)

I made and investigation on the following issue and i found that starts from androidthings lib :

![image](https://user-images.githubusercontent.com/4539769/235347941-892a318c-e8ac-45f1-82d6-f48679fbb6e7.png)

**Comment by xiane** [comment]
Sorry for late reply!
all of this projects are tested on the ODROID board. not tested from the raspberry pi series.
And, you can't run it on the emulator. android things stuffs are not included normal android emulator.
In my opinion, your tested environment didn't have android things frameworks.
Hod did you test it on the pi?

**Comment by xiane** [comment]
Long time no reply. So close it.
